name: cloudwalk
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  connectivity: ^3.0.6
  get_it: ^7.1.3
  geolocator: ^7.3.0
  bot_toast: ^4.0.1
  bloc: ^7.0.0
  dio: ^4.0.0
  flutter_bloc: ^7.0.0
  flutter_dotenv: ^5.0.0
  flutter_easyloading: ^3.0.0
  google_maps_flutter: ^2.0.6
  intl: ^0.17.0
  network_info_plus: ^1.0.2
  sentry_flutter: ^5.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mocktail: ^0.1.0
  very_good_analysis: ^2.1.0

dependency_overrides:
  bloc:
    git:
      url: https://github.com/felangel/bloc
      path: packages/bloc
      ref: e7955c3e357c303ce5661491ba99e68de06cd46b
  flutter_bloc:
    git:
      url: https://github.com/felangel/bloc
      path: packages/flutter_bloc
      ref: e7955c3e357c303ce5661491ba99e68de06cd46b
  bloc_test:
    git:
      url: https://github.com/felangel/bloc
      path: packages/bloc_test
      ref: e7955c3e357c303ce5661491ba99e68de06cd46b

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
